### PR TITLE
FIX apache license 2.0

### PR DESCRIPTION
**Pull request by skliarpawlo**
Update license docs for sparkly

### CODE REVIEW

**Comment by mkamprath** [comment]
Why did you include all the other licenses under the `license` folder? We aren't redistributing those packages, are we?

**Comment by skliarpawlo** [comment]
@mkamprath took spark repo as example, as I understood it's made to show that all used libs liceses are compliant with our library license

**Comment by mkamprath** [comment]
@skliarpawlo In the Apache Spark case, they are actually distributing that code. See their [NOTICE](https://github.com/apache/spark/blob/master/NOTICE) file.

**Comment by skliarpawlo** [comment]
@mkamprath ok will remove

**Comment by skliarpawlo** [comment]
removed. @mkamprath does it looks good other than that?

**Pull request merged**
